import { Footer, FooterNew, Navbar } from "@/components";
// import FooterNew from "../../components/FooterNew";
import React from "react";

const page = () => {
  const list1 = [
    "Opt-In/ Opt-Out for some cookies categories.",
    "View list of cookies generated by the website under each category.",
    "Access the website even if you Opt-Out of all cookies.",
  ];

  const list2 = [
    "See what cookies you've got and delete them on an individual basis.",
    "Block third party cookies",
    "Block cookies from particular site",
    "Block all cookies from being set",
    "Delete all cookies when you close your browser",
  ];

  const list3 = [
    "Help us ‘Remember’ you for log-in purposes",
    "Track user experience and website performance",
    "Manage our marketing relationships",
  ];

  return (
    <div className="text-white ">
      <Navbar />
      <div className="w-[85%] mx-auto">
        <div className="mb-10">
          <h1 className="capitalize font-semibold text-[40px] mb-3">
            cookie policy
          </h1>
          <p className="text-lg font-extralight leading-[22.68px] mb-3">
            This Cookie Policy explains what are cookies, types of cookies, how
            the cookies are categorized and an identifiable individual’s
            (“your”) rights to control Furation Tech’s (“our”, “FurationTech”)
            use of them. This policy was updated on 22nd Dec’21.
          </p>
          <p className="text-lg font-extralight leading-[22.68px] mb-3">
            Cookies are small text files that are stored by your computer (this
            includes smartphones, tablets or any device that you use to access
            the internet) which contains minute pieces of information specific
            to a website or a user.
          </p>
          <p className="text-lg font-extralight leading-[22.68px] mb-3">
            We use cookies to provide the best possible experience on our
            website. Cookies on this site are used to:
          </p>
          <ul className="list-none mb-7">
            {list3.map((item) => {
              return (
                <li
                  className="font-extralight text-xl flex items-center gap-5 mb-5 "
                  key={item}
                >
                  <div className="min-w-[14px] min-h-[14px] rounded-full bg-[#FC3D45] "></div>
                  <p>{item}</p>
                </li>
              );
            })}
          </ul>
          <p className="text-lg font-extralight leading-[22.68px] mb-3">
            If you choose to disable or delete cookies relating to Furation.tech
            we will not remember things about you, and treat you as a first time
            visitor the next time you visit the site.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="font-medium text-[28px] mb-3">What are Cookies</h2>
          <p className="text-lg font-extralight leading-[22.68px]">
            A cookie is a piece of information that webserver sends to an
            identifiable individual’s (“your”) computer (browser file) when a
            website is accessed. It contains information about your visit to
            Furation Tech’s (“our”, “Furation Tech”) web page, as well as any
            other information you have volunteered for. It helps to provide
            additional functionality to the site and analyse site usage more
            accurately. Cookies can gather information about your website usage
            or enable the website to recognise you as an existing customer when
            you return to our website at a later date.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="font-medium text-[28px] mb-3">Types of Cookies</h2>
          <p className="text-lg font-extralight leading-[22.68px]">
            Here's a list of the main types of cookies we use, and what we use
            them for.
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">Session cookie:</h3>
          <p className="text-lg font-extralight leading-[22.68px]">
            Session cookies remains as long as a browsing session is active and
            are intended to avoid user inconvenience during browsing. These
            cookies allow websites to link the actions of a user during a
            browser session and expire at the end of the browsing session.
            Session cookies also assist the user in navigating the website, and
            allow the user to access secure parts of the webpage when logged in.
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">Persistent Cookie:</h3>
          <p className="text-lg font-extralight leading-[22.68px]">
            Persistent cookies are stored on a user’s device even after
            termination of a browsing session. It helps in recalling the
            preferences or actions of the user. Persistent cookies are used for
            a variety of purposes such as retaining the visitor’s language and
            regional preference(s) at the end of each browsing session. It is
            also used to carry out a behavioural analysis in order to enhance
            user experience and convenience, also to provide targeted and
            relevant content to visitors.
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">Third Party Cookies:</h3>
          <p className="text-lg font-extralight mb-6 leading-[22.68px]">
            Third-party cookies are cookies that are set by a website other than
            the current active site. These cookies are generated if the website
            has some content of a third party site or if a user clicks on the
            Third party links provided by the current active website or if the
            user uses their third party website’s credentials to log In to the
            current active website.
          </p>
          <p className="text-lg font-extralight leading-[22.68px]">
            For detailed information on Privacy and Cookie Policy of Third party
            organization, please look into the respective policies at their
            official sites.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="font-medium text-[28px] mb-3">Cookie Category</h2>
          <p className="text-lg font-extralight leading-[22.68px]">
            Cookies are categorized into below based on their purpose and
            functionality under Cookie Settings in cookie banner:
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">
            Strictly Necessary Cookies:
          </h3>
          <p className="text-lg font-extralight leading-[22.68px]">
            These cookies are necessary for the website to function and cannot
            be switched off in our systems. They are usually only set in
            response to actions made by you which amount to a request for
            services, such as setting your privacy preferences, logging in or
            filling in forms. You can set your browser to block or alert you
            about these cookies, but then some parts of the site will not work.
            These cookies do not store any personally identifiable information.
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">
            Social Media Cookies:
          </h3>
          <p className="text-lg font-extralight leading-[22.68px]">
            These cookies are set by a range of social media services that we
            have added to the site to enable you to share our content with your
            friends and networks. They are capable of tracking your browser
            across other sites and building up a profile of your interests. This
            may impact the content and messages you see on other websites you
            visit.
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">Targeting Cookies:</h3>
          <p className="text-lg font-extralight leading-[22.68px]">
            These cookies may be set through our site by our advertising
            partners. They may be used by those companies to build a profile of
            your interests and show you relevant adverts on other sites. They do
            not directly store personal information but, are based on uniquely
            identifying your browser and internet device. If you do not allow
            these cookies, you will experience less targeted advertising.
          </p>
        </div>

        <div className="mb-10">
          <h3 className="font-medium text-[22px] mb-3">Performance Cookies:</h3>
          <p className="text-lg font-extralight leading-[22.68px]">
            These cookies allow us to count visits and traffic sources, so we
            can measure and improve the performance of our site. They help us
            know which pages are the most and least popular and see how visitors
            move around the site. All information these cookies collect is
            aggregated and therefore anonymous. If you do not allow these
            cookies, we will not know when you have visited our site.
          </p>
        </div>

        <div className="mb-10">
          <h2 className="font-medium text-[28px] mb-3">
            Your Choices and Rights
          </h2>
          <p className="text-lg font-extralight mb-6 leading-[22.68px]">
            There are ways you can control and manage cookies on your device.
            Please remember that any setting changed by you will apply to all
            websites you visit unless you choose to block cookies from any
            particular site.
          </p>
          <p className="text-lg font-extralight mb-7 leading-[22.68px]">
            You will have below controls on cookies generated by our site
            through Cookie Settings as below:
          </p>

          <ul className="list-none mb-7">
            {list1.map((item) => {
              return (
                <li
                  className="font-extralight text-xl flex items-center mb-5"
                  key={item}
                >
                  <div className="min-w-[14px] min-h-[14px] rounded-full bg-[#FC3D45] mr-5 "></div>{" "}
                  {item}
                </li>
              );
            })}
          </ul>

          <p className="text-lg font-extralight mb-7 leading-[22.68px]">
            Thus, you can control your cookie choices using above or
            system/browser settings as below:
          </p>

          <ul className="list-none mb-7">
            {list2.map((item) => {
              return (
                <li
                  className="font-extralight text-xl flex items-center gap-5 mb-5 "
                  key={item}
                >
                  <div className="min-w-[14px] min-h-[14px] rounded-full bg-[#FC3D45] "></div>
                  <p>{item}</p>
                </li>
              );
            })}
          </ul>
        </div>

        <div className="mb-10">
          <h2 className="font-medium text-[28px] mb-3">
            Updates to this Cookie Policy
          </h2>
          <p className="text-lg font-extralight mb-6 leading-[22.68px]">
            This Cookie Policy may be updated periodically. We will encourage
            you to check for changes to this Cookie Policy occasionally, which
            will be available at: https://www.furation.tech/cookie-policy/
          </p>
          <p className="text-lg font-extralight mb-6 leading-[22.68px]">
            To get further information on Furation Tech’s personal data
            collection and processing please check at:
            https://www.furation.tech/privacy-policy/
          </p>
          <p className="text-lg font-extralight mb-6 leading-[22.68px]">
            On some occasions, we may also actively advise you of specific data
            handling activities or significant changes to this Cookie Policy, as
            required by the applicable law.
          </p>
        </div>

        <div className="mb-20">
          <h2 className="font-medium text-[28px] mb-3">
            Updates to this Cookie Policy
          </h2>
          <p className="text-lg font-extralight mb-6 leading-[22.68px]">
            If you have any question about this Cookies Policy or wish to
            contact us for any reason in relation to our personal data
            processing, please contact us at : dpo@furation.tech
          </p>
        </div>
      </div>
      <div className="bg-[#2D2D2D]">
        <FooterNew />
      </div>
    </div>
  );
};

export default page;
